### ISSUE TITLE
output numbering

### ISSUE THREAD

**Issue by jcauzid** [hameye/findcoord#13]
Le script utilise la dernière ligne pour donner le préfixe des points à écrire dans output. Du coup, il reprend la dernière valeur avec son numéro. Dans notre exemple, il prendra "Measurement50" et numérotera les mesures dans le fichier output de "Measurement501" à "Measurement5050"

Il faudrait changer la ligne 129, dans extract_coordinates(self): remplacer prefix par prefix[:-2]

Ou alors ne pas faire numéroter dans le fichier input mais c'est moins pratique pour l'utilisateur.

**Comment by hameye** [comment]
@jcauzid Le script prend le nom commun entre les deux dernières lignes. Cela signifie que les deux dernieres lignes ont en commun 'Measurement50'

**Comment by jcauzid** [comment]
Le test avec les deux fichiers suivants. Le fichier output a bien un radical évalué avec la dernière ligne seulement. Si c'étaient les deux dernières lignes, on aurait un radical "Measurement5" et pas "Measurement56". Ce n'est pas bien grave. Si je trouve une astuce, je te fais signe.

[SAA01_input.txt](https://github.com/hameye/findcoord/files/5357083/SAA01_input.txt)
[SAA01_output.txt](https://github.com/hameye/findcoord/files/5357087/SAA01_output.txt)

**Comment by hameye** [comment]
@jcauzid 
Je viens de faire le test, j'ai bien un radical "Measurement5", mais bon ca ne va toujours pas ! Je vais réfléchir à cela

**Comment by hameye** [comment]
@jcauzid Le fix est fait, c'est dispo sur la branche dev
